name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    uses: and3rn3t/.github/.github/workflows/reusable-python-test.yml@bac71674cf57c550774f71a70e32a5bb7bec48ad # v1
